/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.movie.cinema;

import com.movie.cinema.db.AccountDao;
import com.movie.cinema.model.Account;
import java.awt.BorderLayout;
import javax.swing.Box;
import javax.swing.JComponent;

/**
 *
 * @author Tianyang Li
 */
public class MainFrame extends javax.swing.JFrame {
    
    LoginPanel loginPanel; // login panel
    Box verticalBox;
    Box horizontalBox;
     
    ShowPanel showPanel; // Movie Information List
    Account acc; // Current Login User
    
    AccountDao accDao = new AccountDao();
    
    private static MainFrame instance;
    public static MainFrame getInstance(){
        return instance;
    }

    /**
     * Creates new form LoginFrame
     */
    public MainFrame() {
        instance = this;
        showPanel = new ShowPanel();
        loginPanel = new LoginPanel(this);
        verticalBox = Box.createVerticalBox();
        horizontalBox = Box.createHorizontalBox();
        initComponents();
        setLocationRelativeTo(null);
        
        mainPanel.setLayout(new BorderLayout());
        
        changePanel("login");
    }
    
    /**
     * Set login user information
     * @param acc 
     */
    public void setAccount(Account acc){
        if(acc != null){
            
            this.acc = acc;
            toListItem.setEnabled(true);
            orderListItem.setEnabled(true);
            accountItem.setEnabled(true);
        }else{
            this.acc = acc;
            toListItem.setEnabled(false);
            orderListItem.setEnabled(false);
            accountItem.setEnabled(false);
        }
    }
    
    /**
     * Switch between different interfaces
     * @param name 
     */
    public void changePanel(String name){
        
        switch(name){
            case "login":
                changePanel(loginPanel);
                break;
            case "show":
                changePanel(showPanel);
                break;
            case "order":
                changePanel(new OrdersPanel());
                break;
            default:
                changePanel(loginPanel);
        }
        
    }
    public void changePanel(JComponent component){
        mainPanel.setVisible(false);
        mainPanel.removeAll();
        verticalBox.removeAll();
        horizontalBox.removeAll();
        
        verticalBox.add(Box.createVerticalGlue());
        
        verticalBox.add(component);
        
        
        verticalBox.add(Box.createVerticalGlue());
        
        horizontalBox.add(Box.createHorizontalGlue());
        horizontalBox.add(verticalBox);
        horizontalBox.add(Box.createHorizontalGlue());
        mainPanel.add(horizontalBox, BorderLayout.CENTER);
        
        mainPanel.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        accountItem = new javax.swing.JMenuItem();
        orderListItem = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        toListItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(805, 605));

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Account");

        accountItem.setText("Account Info");
        accountItem.setEnabled(false);
        accountItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountItemActionPerformed(evt);
            }
        });
        jMenu1.add(accountItem);

        orderListItem.setText("My Orders");
        orderListItem.setEnabled(false);
        orderListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListItemActionPerformed(evt);
            }
        });
        jMenu1.add(orderListItem);

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");

        toListItem.setText("ListPanel");
        toListItem.setEnabled(false);
        toListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toListItemActionPerformed(evt);
            }
        });
        jMenu2.add(toListItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // User logs out
    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        // TODO add your handling code here:
        changePanel("login");
        setAccount(null);
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void toListItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toListItemActionPerformed
        // TODO add your handling code here:
        changePanel("show");
    }//GEN-LAST:event_toListItemActionPerformed

    private void orderListItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListItemActionPerformed
        // TODO add your handling code here:
        changePanel("order");
    }//GEN-LAST:event_orderListItemActionPerformed

    private void accountItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountItemActionPerformed
        // TODO add your handling code here:
        changePanel(new AccountPanel(acc));
    }//GEN-LAST:event_accountItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accountItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem orderListItem;
    private javax.swing.JMenuItem toListItem;
    // End of variables declaration//GEN-END:variables
}
