/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.movie.cinema;

import com.movie.cinema.db.OrderDao;
import com.movie.cinema.model.Cinema;
import com.movie.cinema.model.Movie;
import com.movie.cinema.model.Order;
import com.movie.cinema.model.Schedule;

/**
 *
 * @author zhch
 */
public class OrderGrid extends javax.swing.JPanel {

    // 订票数据 dao
    OrderDao orderDao = new OrderDao();
    // 订票信息
    Order order;
    
    /**
     * Creates new form OrderGrid
     */
    public OrderGrid(Order order, Schedule schedule, Cinema cinema, Movie movie) {
        this.order = order;
        
        initComponents();
        if(order.getStatus() == 0){
            statusL.setText("status: not used");
        }else{
            statusL.setText("status:used");
        }
        if(schedule != null){
            timeL.setText(schedule.getShowtime());
        }
        if(cinema != null){
            cinemaNameL.setText(cinema.getName());
        }
        if(movie != null){
            movieNameL.setText(movie.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieNameL = new javax.swing.JLabel();
        cinemaNameL = new javax.swing.JLabel();
        timeL = new javax.swing.JLabel();
        useBtn = new javax.swing.JButton();
        statusL = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        movieNameL.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        movieNameL.setText("movie name");

        cinemaNameL.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        cinemaNameL.setText("cinema");

        timeL.setText("2020-12-12 12:12");

        useBtn.setText("Use");
        useBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useBtnActionPerformed(evt);
            }
        });

        statusL.setText("status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movieNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(statusL))
                    .addComponent(cinemaNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useBtn))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeL)
                    .addComponent(statusL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinemaNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useBtnActionPerformed
        order.setStatus(1);
        int res = orderDao.updateStatus(order);
        if(res > 0){
            useBtn.setEnabled(false);
            BaseDialog.showInfo("Use ticket successfully.");
        }else{
            BaseDialog.showErr("Use ticket failed.");
        }
    }//GEN-LAST:event_useBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinemaNameL;
    private javax.swing.JLabel movieNameL;
    private javax.swing.JLabel statusL;
    private javax.swing.JLabel timeL;
    private javax.swing.JButton useBtn;
    // End of variables declaration//GEN-END:variables
}
