/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.movie.cinema;

import com.movie.cinema.db.CinemaDao;
import com.movie.cinema.db.ScheduleDao;
import com.movie.cinema.model.Cinema;
import com.movie.cinema.model.Movie;
import com.movie.cinema.model.Schedule;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Shijie Ma
 */
public class SchedulePanel extends javax.swing.JPanel {
    
    ScheduleDao scheduleDao = new ScheduleDao();
    CinemaDao cinemaDao = new CinemaDao();

    /**
     * Creates new form SchedulePanel
     * @param movie
     */
    public SchedulePanel(Movie movie) {
        initComponents();
        List<Schedule> list = scheduleDao.getSchedules(movie.getId());
        List<Integer> cinemaIds = new ArrayList<>();
        list.forEach(schedule -> {
            cinemaIds.add(schedule.getCinemaid());
        });
        System.out.println("movie id:" + movie.getId() + " schedule list size:" + list.size());
        conPanel.setLayout(new GridLayout(list.size(), 1));
        Map<Integer, Cinema> cinemas = cinemaDao.getCinemasMap(cinemaIds);
        list.stream().map(schedule -> new ScheduleGrid(schedule,movie, cinemas.get(schedule.getCinemaid()))).forEachOrdered(grid -> {
            conPanel.add(grid);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        conPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout conPanelLayout = new javax.swing.GroupLayout(conPanel);
        conPanel.setLayout(conPanelLayout);
        conPanelLayout.setHorizontalGroup(
            conPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        conPanelLayout.setVerticalGroup(
            conPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(conPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conPanel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
